[news1]
date="Sep 2024"
body="Il corso \"Logica, Modelli di Calcolo e Metodi Probabilistici per l'Informatica\" Inizierà il 25-09-2024. Per maggiori informazioni visitare la [pagina del corso]({{< ref \"teaching/courses/lcp2425\">}})."
type="Teaching"
